name: docker-snapshot
on:
  push:
  schedule:
  - cron: "0 12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Build with Maven
      run: mvn -B -DskipTests=true -f pom.xml clean install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 image
      run: |
        cd server
        docker build -f src/main/docker/Dockerfile.amd64 -t piranhacloud/server:amd64-snapshot .
        docker push piranhacloud/server:amd64-snapshot
    - name: Build ARM32v6 image
      run: |
        cd server
        docker build -f src/main/docker/Dockerfile.ARM32v6 -t piranhacloud/server:arm32v6-snapshot .
        docker push piranhacloud/server:arm32v6-snapshot
    - name: Create multi-arch manifest
      run: |
        cd server
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create piranhacloud/server:snapshot \
          piranhacloud/server:amd64-snapshot \
          piranhacloud/server:arm32v6-snapshot
        docker manifest annotate piranhacloud/server:snapshot \
          piranhacloud/server:amd64-snapshot --os linux --arch amd64
        docker manifest annotate piranhacloud/server:snapshot \
          piranhacloud/server:arm32v6-snapshot --os linux --arch arm
        docker manifest push piranhacloud/server:snapshot
