name: nightly
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn --no-transfer-progress -B -DskipTests=true -P '!test' deploy
      env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Analyze with SonarCloud
      run: |
        mvn --no-transfer-progress -B install verify site \
        sonar:sonar -Dsonar.projectKey=piranhacloud_piranha \
        -Dsonar.organization=piranhacloud -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.login=${{ secrets.SONAR_LOGIN }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 170 days with no activity. Remove stale label or comment or this will be closed in 10 days'
        days-before-stale: 170
        days-before-close: 10
