name: release
on:
  push:
    tags:        
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up Java 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 16
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Build with Maven
      run: mvn --no-transfer-progress -B -DskipTests=true install
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 Docker image
      run: |
        cd server
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}}
        docker build -f src/main/docker/Dockerfile.amd64 -t piranhacloud/server:amd64-$VERSION .
        docker push piranhacloud/server:amd64-$VERSION
    - name: Create multi-arch manifest
      run: |
        cd server
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}}
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create piranhacloud/server:$VERSION \
          piranhacloud/server:amd64-$VERSION
        docker manifest annotate piranhacloud/server:$VERSION \
          piranhacloud/server:amd64-$VERSION --os linux --arch amd64
        docker manifest push piranhacloud/server:$VERSION
    - name: Build with Maven
      run: |
        export MAVEN_OPTS='--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED'
        mvn --no-transfer-progress -B -DskipTests=true -P 'release,!test' clean deploy
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
