name: tck-servlet
on:
  schedule:
  - cron: "0 2 * * 1"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '1.8' ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup for TCK
      run: mvn -B -DskipTests=true install
    - name: Run TCK
      run: mvn -amd -B -P tck -pl tck/servlet verify
