name: tck
on:
  push:
   branches:
    - master
  schedule:
  - cron: "0 2 * * 1"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup for TCK
      run: mvn -B -DskipTests=true install
    - name: Run TCK
      run: mvn -amd -B -P tck -pl tck/servlet verify
